# Generated by Django 2.1.1 on 2018-12-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('games_played_center', models.IntegerField(default=0)),
                ('games_played_left_wing', models.IntegerField(default=0)),
                ('games_played_right_wing', models.IntegerField(default=0)),
                ('games_played_defense', models.IntegerField(default=0)),
                ('games_played_goalie', models.IntegerField(default=0)),
                ('games_played_utility', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NHLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=3)),
                ('games_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Scraper.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Scraper.FantasyTeam'),
        ),
        migrations.AddField(
            model_name='player',
            name='nhl_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Scraper.NHLTeam'),
        ),
    ]
