# Generated by Django 2.1.1 on 2018-12-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
    ]
