# Generated by Django 2.1.1 on 2018-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0003_nhlteam_espn_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='espn_position_id',
            field=models.IntegerField(default=0),
        ),
    ]
