# Generated by Django 2.1.1 on 2018-12-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0005_fantasyteam_players_last_scraped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='players_last_scraped',
        ),
    ]
